"use client";

import { Bar, BarChart, CartesianGrid, XAxis, YAxis } from "recharts";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/primitives/card";
import {
  ChartContainer,
  ChartTooltip,
  ChartTooltipContent,
} from "@/components/primitives/chart";
import { SPACE_REVENUE_CHART_CONFIG } from "../constants";

type SpacePerformanceItem = {
  id: string;
  title: string;
  totalRevenue: number | null;
};

type Props = {
  data: SpacePerformanceItem[];
};

export default function RevenueChart({ data }: Props) {
  const chartData = data.map((space) => ({
    name:
      space.title.length > 15 ? space.title.slice(0, 15) + "..." : space.title,
    fullName: space.title,
    revenue: Number(space.totalRevenue ?? 0),
  }));

  return (
    <Card>
      <CardHeader>
        <CardTitle>Revenue by Space</CardTitle>
        <CardDescription>
          Total revenue generated by each of your spaces
        </CardDescription>
      </CardHeader>
      <CardContent>
        <ChartContainer
          config={SPACE_REVENUE_CHART_CONFIG}
          className="h-[300px] w-full"
        >
          <BarChart
            data={chartData}
            layout="vertical"
            margin={{ left: 0, right: 16 }}
          >
            <CartesianGrid horizontal={false} />
            <YAxis
              dataKey="name"
              type="category"
              tickLine={false}
              axisLine={false}
              tickMargin={8}
              width={100}
              className="text-xs"
            />
            <XAxis
              type="number"
              tickLine={false}
              axisLine={false}
              tickMargin={8}
              tickFormatter={(value) =>
                new Intl.NumberFormat("en-US", {
                  style: "currency",
                  currency: "USD",
                  notation: "compact",
                }).format(value)
              }
            />
            <ChartTooltip
              cursor={false}
              content={
                <ChartTooltipContent
                  hideLabel
                  formatter={(value, _name, item) => (
                    <div className="flex flex-col gap-0.5">
                      <span className="font-medium">
                        {item.payload.fullName}
                      </span>
                      <span className="text-muted-foreground">
                        {new Intl.NumberFormat("en-US", {
                          style: "currency",
                          currency: "USD",
                        }).format(Number(value))}
                      </span>
                    </div>
                  )}
                />
              }
            />
            <Bar
              dataKey="revenue"
              fill="var(--color-revenue)"
              radius={[0, 4, 4, 0]}
            />
          </BarChart>
        </ChartContainer>
      </CardContent>
    </Card>
  );
}
