import SpaceCard from "./space-card";

const billboards = [
  {
    id: 1,
    address: "123 Main St, Charlottesville, VA",
    size: "14x48 ft",
    type: "Digital",
    monthlyRate: "$4,500",
    status: "Available",
  },
  {
    id: 2,
    address: "456 University Ave, Charlottesville, VA",
    size: "10x30 ft",
    type: "Static",
    monthlyRate: "$2,800",
    status: "Booked",
  },
  {
    id: 3,
    address: "789 Emmet St N, Charlottesville, VA",
    size: "12x40 ft",
    type: "Digital",
    monthlyRate: "$5,200",
    status: "Available",
  },
  {
    id: 4,
    address: "321 Barracks Rd, Charlottesville, VA",
    size: "14x48 ft",
    type: "Static",
    monthlyRate: "$3,900",
    status: "Available",
  },
  {
    id: 5,
    address: "555 Ivy Rd, Charlottesville, VA",
    size: "10x36 ft",
    type: "Digital",
    monthlyRate: "$4,100",
    status: "Maintenance",
  },
  {
    id: 6,
    address: "901 Preston Ave, Charlottesville, VA",
    size: "12x24 ft",
    type: "Static",
    monthlyRate: "$2,200",
    status: "Available",
  },
  {
    id: 7,
    address: "1400 W Main St, Charlottesville, VA",
    size: "14x48 ft",
    type: "Digital",
    monthlyRate: "$6,200",
    status: "Available",
  },
  {
    id: 8,
    address: "2000 Jefferson Park Ave, Charlottesville, VA",
    size: "10x30 ft",
    type: "Static",
    monthlyRate: "$2,500",
    status: "Available",
  },
  {
    id: 9,
    address: "Rt 29 N & Rio Rd, Charlottesville, VA",
    size: "14x48 ft",
    type: "Digital",
    monthlyRate: "$7,800",
    status: "Available",
  },
  {
    id: 10,
    address: "250 Bypass, Charlottesville, VA",
    size: "12x40 ft",
    type: "Static",
    monthlyRate: "$3,600",
    status: "Booked",
  },
  {
    id: 11,
    address: "Emmet St & Barracks Rd, Charlottesville, VA",
    size: "14x48 ft",
    type: "Digital",
    monthlyRate: "$8,500",
    status: "Available",
  },
  {
    id: 12,
    address: "Fontaine Ave, Charlottesville, VA",
    size: "10x36 ft",
    type: "Static",
    monthlyRate: "$2,900",
    status: "Available",
  },
  {
    id: 13,
    address: "Pantops Mountain, Charlottesville, VA",
    size: "14x48 ft",
    type: "Digital",
    monthlyRate: "$5,900",
    status: "Available",
  },
  {
    id: 14,
    address: "5th Street Extended, Charlottesville, VA",
    size: "12x24 ft",
    type: "Static",
    monthlyRate: "$2,100",
    status: "Available",
  },
  {
    id: 15,
    address: "Downtown Mall, Charlottesville, VA",
    size: "10x20 ft",
    type: "Digital",
    monthlyRate: "$4,800",
    status: "Booked",
  },
  {
    id: 16,
    address: "I-64 Exit 118, Charlottesville, VA",
    size: "14x48 ft",
    type: "Digital",
    monthlyRate: "$9,200",
    status: "Available",
  },
  {
    id: 17,
    address: "Rte 250 E, Charlottesville, VA",
    size: "12x40 ft",
    type: "Static",
    monthlyRate: "$3,400",
    status: "Available",
  },
  {
    id: 18,
    address: "Millmont St, Charlottesville, VA",
    size: "10x30 ft",
    type: "Static",
    monthlyRate: "$2,300",
    status: "Maintenance",
  },
  {
    id: 19,
    address: "Hydraulic Rd, Charlottesville, VA",
    size: "14x48 ft",
    type: "Digital",
    monthlyRate: "$6,800",
    status: "Available",
  },
  {
    id: 20,
    address: "Seminole Trail, Charlottesville, VA",
    size: "12x36 ft",
    type: "Static",
    monthlyRate: "$3,200",
    status: "Available",
  },
  {
    id: 21,
    address: "Greenbrier Dr, Charlottesville, VA",
    size: "10x24 ft",
    type: "Static",
    monthlyRate: "$1,900",
    status: "Available",
  },
];

export default function Page() {
  return (
    <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
      {billboards.map((billboard) => (
        <SpaceCard key={billboard.id} {...billboard} />
      ))}
    </div>
  );
}
